version: '3'
services:

  builder:
    build:
      context: ./
      dockerfile: Dockerfile.builder
#     volumes:
#       - "./:/app"
    volumes:
      - "./:/app"
#       - "/app/node_modules"
    environment:
      REACT_APP_GFS_FS_NAME: "gfs1"
      REACT_APP_GFS_API_HOST: "server"
      REACT_APP_GFS_API_PORT: "5000"
      REACT_APP_GFS_API_USERNAME: ""
      REACT_APP_GFS_API_PASSWORD: ""
      REACT_APP_GFS_WS_HOST: "server"
      REACT_APP_GFS_WS_PORT: "5002"
      REACT_APP_GFS_WS_USERNAME: ""
      REACT_APP_GFS_WS_PASSWORD: ""
    restart: on-failure
    hostname: "builder"
    networks:
      - gremlinfs
    expose:
      - 3000
    ports:
      - 3000:3000
    stdin_open: true

networks:
  gremlinfs: 
    external:
      name: gremlinfs
